### ISSUE TITLE
Missing css

### ISSUE THREAD

**Issue by AndyShad** [olalonde/handlebars-paginate#16]
Hello, where is the class  named pagination-centered

**Comment by jimf** [comment]
Hi Andy. The example might be a tad deceptive. This plugin only handles pagination logic. It's not a full blown pagination solution. It's meant to be framework / library agnostic. Markup and styles are left to the user.

**Comment by olalonde** [comment]
FWIF I think I used bootstrap 3 classes in the example but yes, bootstrap CSS would have to be included outside this module.

**Comment by AndyShad** [comment]
Thank you for your reply.Your work is very good. I know what you mean.  I
'll handler the css.
