### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by benbagley** [olalonde/handlebars-paginate#21]
Just giving this another shot and I'm getting the following

```
ReferenceError: template is not defined
```

I have the following

`app.js`

```
const paginate = require('handlebars-paginate');

hbs.registerHelper('paginate', paginate);
```

`index.hbs`

```
<nav aria-label="Page navigation">
	  <ul class="pagination">
	    {{#paginate pagination type="first"}}
	    <li class="page-item{{#if disabled}} disabled{{/if}}">
	      <a class="page-link" href="?page={{n}}" aria-label="First">
	        <span aria-hidden="true">&laquo;</span>
	        <span class="sr-only">First</span>
	      </a>
	    </li>
	    {{/paginate}}
	    {{#paginate pagination type="previous"}}
	    <li class="page-item{{#if disabled}} disabled{{/if}}">
	      <a class="page-link" href="?page={{n}}" aria-label="Previous">
	        <span aria-hidden="true">&lsaquo;</span>
	        <span class="sr-only">Previous</span>
	      </a>
	    </li>
	    {{/paginate}}
	    {{#paginate pagination type="middle" limit="10"}}
	    <li class="page-item"><a class="page-link{{#if disabled}} disabled{{/if}}" href="?page={{n}}">{{n}}</a></li>
	    {{/paginate}}
	    {{#paginate pagination type="next"}}
	    <li class="page-item{{#if disabled}} disabled{{/if}}">
	      <a class="page-link" href="?page={{n}}" aria-label="Next">
	        <span aria-hidden="true">&rsaquo;</span>
	        <span class="sr-only">Next</span>
	      </a>
	    </li>
	    {{/paginate}}
	    {{#paginate pagination type="last"}}
	    <li class="page-item{{#if disabled}} disabled{{/if}}">
	      <a class="page-link" href="?page={{n}}" aria-label="Last">
	        <span aria-hidden="true">&raquo;</span>
	        <span class="sr-only">Last</span>
	      </a>
	    </li>
	    {{/paginate}}
	  </ul>
	</nav>
```

`routes.js`

```
router.get('/dashboard', ensureAuthenticated, (req, res) => {
  const html = template({pagination: {
    page: parseInt(req.query.page) || 1,
    pageCount: parseInt(req.query.limit) || 6
  }});

  User.find({}, function(err, users) {
    res.render('dashboard/index.hbs', {
      pageTitle: 'Dashboard',
      users: users,
      pagination: {
        page: page,
        pageCount: pageCount
      }
    });
  });
});
```

**Comment by jimf** [comment]
In the README, `template` is a standin for whatever your template is. There are a number of ways to convert Handlebars templates into JavaScript, which is why the README doesn't spell that out. But the implication is that `template` should be replaced by whatever method you're using at the JS level to invoke your Handlebars templates.

**Comment by benbagley** [comment]
That's not very clear in the docs though, easy to get confused when you get errors like this. So as I'm using handlebars "hbs" package it would be something like

```
const html = hbs({pagination: {
    page: parseInt(req.query.page) || 1,
    pageCount: parseInt(req.query.limit) || 6
}});
```

?

**Comment by jimf** [comment]
I'm not familiar with the hbs package. So long as you have handlebars-paginate registered, you're using it in your templates with the name you registered it under, and you're providing it with the context it expects (i.e., the `pagination` object), it should do what it's designed to do.

Once again, `pagination.pageCount` is the number of pages of content that you have. __NOT__ the number of pages you want to display per page. handlebars-paginate is completely oblivious to the latter.

**Comment by benbagley** [comment]
```
Once again, pagination.pageCount is the number of pages of content that you have. NOT the number of pages you want to display per page. handlebars-paginate is completely oblivious to the latter.
```

Isn't that the whole reason for a pagination though? To filter x amount of records per page?

**Comment by jimf** [comment]
handlebars-paginate is a pagination state renderer. It doesn't itself implement the details necessary for fetching collections N records at a time. Those details are up to the user, who must then relay the state accordingly to handlebars-paginate to then render the state accordingly. All handlebars-paginate is concerned with is what the current page and total number of pages are.
