### ISSUE TITLE
Installation via Bower

### ISSUE THREAD

**Issue by lauterry** [olalonde/handlebars-paginate#3]
Please make your project available via Bower

```bower install handlebars-paginate```

**Comment by rflnogueira** [comment]
:+1:

**Comment by olalonde** [comment]
I'm not sure how to do this...can someone make a pull request or do it for me?

**Comment by rflnogueira** [comment]
I can do it.

FYI http://bower.io/docs/creating-packages/

Really nice plugin BTW :)

**Comment by rflnogueira** [comment]
The package is registered, you can now just accept the pull request.

**Comment by olalonde** [comment]
Done, thanks.
